### ISSUE TITLE
Implement e2e test that verifies Citizen table is updated when existing citizen information is altered before saving the complaint

### ISSUE THREAD

**Issue by alayor-westga** [alayor-westga/CS6290_PSPro#57]
We may just need to add E2E tests.

**Comment by mhamel1** [comment]
For discussion... I think this may have already been covered in this e2e test: Scenario: Add new complaint successfully -> Given this citizen info is entered.

Although, we might want to add a new issue that reads: "Add e2e test that verifies Citizen table is updated when existing citizen information is altered before saving the complaint"

**Comment by alayor-westga** [comment]
Sounds good. I'll add that issue.
